# Generated by Django 5.2.5 on 2025-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], max_length=32),
        ),
    ]
